export const CMS_PAGES = {
  HISTORY_OF_GATKA: "HISTORY_OF_GATKA",
  HISTORY_OF_ASSOCIATION: "HISTORY_OF_ASSOCIATION",
  DRESS_CODE: "DRESS_CODE",
  TYPES_OF_TOURNAMENTS: "TYPES_OF_TOURNAMENTS",
  OUR_ACHIEVEMENTS: "OUR_ACHIEVEMENTS",
} as const;

export type CmsPageSlug = (typeof CMS_PAGES)[keyof typeof CMS_PAGES];

export const CMS_PAGE_SLUGS = Object.values(CMS_PAGES);

export const NATIONAL_ONLY_CMS_PAGES = new Set<string>([
  CMS_PAGES.HISTORY_OF_GATKA,
  CMS_PAGES.DRESS_CODE,
  CMS_PAGES.TYPES_OF_TOURNAMENTS,
]);

export const STATE_ONLY_CMS_PAGES = new Set<string>([
  CMS_PAGES.HISTORY_OF_ASSOCIATION,
  CMS_PAGES.OUR_ACHIEVEMENTS,
]);
