import { Router } from "express";
import { healthRouter } from "./health.js";
import { authRouter } from "./auth.js";
import { statesRouter } from "./states.js";
import { districtsRouter } from "./districts.js";
import { trainingCentersRouter } from "./trainingCenters.js";
import { settingsRouter } from "./settings.js";
import { ageCategoriesRouter } from "./ageCategories.js";
import { eventGroupsRouter } from "./eventGroups.js";
import { sessionsRouter } from "./sessions.js";
import { paymentsRouter } from "./payments.js";
import { playersRouter } from "./players.js";
import { competitionsRouter } from "./competitions.js";
import { tournamentRegsRouter } from "./tournamentRegs.js";
import { participationRouter } from "./participation.js";
import { campsRouter } from "./camps.js";
import { attendanceRouter } from "./attendance.js";
import { resultsRouter } from "./results.js";
import { noticesRouter } from "./notices.js";
import { migrationRouter } from "./migration.js";
import { complaintsRouter } from "./complaints.js";
import { smsRouter } from "./sms.js";
import { verifyRouter } from "./verify.js";
import { adminUsersRouter } from "./adminUsers.js";
import { usersRouter } from "./users.js";
import { reportsRouter } from "./reports.js";
import { bannersRouter } from "./banners.js";
import { uploadsRouter } from "./uploads.js";
import { profilePhotosRouter } from "./profilePhotos.js";
import { statusRouter } from "./status.js";
import { stateRegistrationsRouter } from "./stateRegistrations.js";
import { districtRegistrationsRouter } from "./districtRegistrations.js";
import { galleryImagesRouter } from "./galleryImages.js";
import { messagesRouter } from "./messages.js";
import { membershipsRouter } from "./memberships.js";
export const apiRouter = Router();

apiRouter.use(healthRouter);
apiRouter.use("/auth", authRouter);
apiRouter.use("/states", statesRouter);
apiRouter.use("/districts", districtsRouter);
apiRouter.use("/training-centers", trainingCentersRouter);
apiRouter.use("/settings", settingsRouter);
apiRouter.use("/age-categories", ageCategoriesRouter);
apiRouter.use("/event-groups", eventGroupsRouter);
apiRouter.use("/sessions", sessionsRouter);
apiRouter.use("/payments", paymentsRouter);
apiRouter.use("/players", playersRouter);
apiRouter.use("/competitions", competitionsRouter);
apiRouter.use("/tournament-registrations", tournamentRegsRouter);
apiRouter.use("/participation", participationRouter);
apiRouter.use("/camps", campsRouter);
apiRouter.use("/attendance", attendanceRouter);
apiRouter.use("/results", resultsRouter);
apiRouter.use("/notices", noticesRouter);
apiRouter.use("/migration", migrationRouter);
apiRouter.use("/complaints", complaintsRouter);
apiRouter.use("/sms", smsRouter);
apiRouter.use("/verify", verifyRouter);
apiRouter.use("/admin/users", adminUsersRouter);
apiRouter.use("/users", usersRouter);
apiRouter.use("/reports", reportsRouter);
apiRouter.use("/banners", bannersRouter);
apiRouter.use("/uploads", uploadsRouter);
apiRouter.use("/profile-photos", profilePhotosRouter);
apiRouter.use("/status", statusRouter);
apiRouter.use("/state-registrations", stateRegistrationsRouter);
apiRouter.use("/district-registrations", districtRegistrationsRouter);
apiRouter.use("/gallery", galleryImagesRouter);
apiRouter.use("/messages", messagesRouter);
apiRouter.use("/memberships", membershipsRouter);
