-- CreateTable
CREATE TABLE "RolePaymentFeeConfig" (
    "role" "Role" NOT NULL,
    "feeAmountPaise" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RolePaymentFeeConfig_pkey" PRIMARY KEY ("role")
);

-- Dummy fees (paise) for each role except NATIONAL_ADMIN
INSERT INTO "RolePaymentFeeConfig" ("role", "feeAmountPaise", "createdAt", "updatedAt") VALUES
('STATE_ADMIN', 500100, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('DISTRICT_ADMIN', 300200, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('TRAINING_CENTER', 250300, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('COACH', 200400, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('REFEREE', 150500, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('PLAYER', 100600, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('VOLUNTEER', 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
